name: sw_project
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
    # 소셜 로그인
  google_sign_in: ^6.2.1

    # API 통신
  dio: ^5.4.3+1

    # 아이콘 사용
  font_awesome_flutter: ^10.7.0

  cached_network_image: ^3.3.1

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"

  flutter_native_splash: ^2.4.0
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # assets 폴더를 선언하는 부분
  assets:
    - assets/images/
    - assets/icons/
    - assets/icon/

  # fonts 폴더를 선언하는 부분
  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Regular.ttf
        - asset: assets/fonts/Pretendard-Medium.ttf
          weight: 500
        - asset: assets/fonts/Pretendard-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Pretendard-Bold.ttf
          weight: 700